### ISSUE TITLE
Could you share you banner logo?

### ISSUE THREAD

**Issue by colonelrascals** [zaiste/.doom.d#1]
I love your banner logo when launching doom...any chance you could share it?

**Comment by zaiste** [comment]
@colonelrascals sure, I'm currently on holiday. Can this wait till the next week ?

**Comment by colonelrascals** [comment]
absolutely! Enjoy your holiday!

**Comment by zaiste** [comment]
Here it is.

```elisp
 +doom-dashboard-banner-file (expand-file-name "logo.png" doom-private-dir)
```

![logo](https://user-images.githubusercontent.com/200613/63640236-0efb6680-c69e-11e9-90f3-24b64adecc1b.png)
